export const GET_RESOURCES = 'GET_RESOURCES';
export const SAVE_RESOURCES = 'SAVE_RESOURCES';
export const SAVE_RESOURCES_ERROR = 'SAVE_RESOURCES_ERROR';
export const FILTER_CONTAINS = 'FILTER_CONTAINS';
export const FILTER_BY_LANGUAGE = 'FILTER_BY_LANGUAGE';
export const FILTER_BY_MODULE = 'FILTER_BY_MODULE';
export const ALL = 'ALL';
